defmodule SleeperPlayerApiWeb.TradeControllerTest do
  # Points the Sleeper client at Bypass via the shared `:sleeper_base_url`
  # Application env, same as the intel controller suite — so not async.
  use SleeperPlayerApiWeb.ConnCase, async: false

  alias SleeperPlayerApi.Intel
  alias SleeperPlayerApi.Repo
  alias SleeperPlayerApi.Sleeper.{Player, Position}

  @league "424242"
  @me "111"
  @them "222"

  setup do
    bypass = Bypass.open()
    Application.put_env(:sleeper_player_api, :sleeper_base_url, "http://localhost:#{bypass.port}")
    on_exit(fn -> Application.delete_env(:sleeper_player_api, :sleeper_base_url) end)
    {:ok, bypass: bypass}
  end

  defp seed_player(player_id, abbreviation) do
    position =
      Repo.get_by(Position, abbreviation: abbreviation) ||
        Repo.insert!(%Position{abbreviation: abbreviation})

    # `id` is not autogenerated — it is the Sleeper id, set explicitly.
    Repo.insert!(%Player{
      id: String.to_integer(player_id),
      player_id: player_id,
      full_name: "P #{player_id}",
      player_json: "{}",
      first_name: "P",
      last_name: player_id,
      search_first_name: "p",
      search_last_name: player_id,
      search_full_name: "p #{player_id}",
      position_id: position.id
    })
  end

  defp seed_value(player_id, value) do
    Intel.upsert_player_values([
      %{
        player_id: String.to_integer(player_id),
        source: "keeptradecut:sf",
        value: value,
        overall_rank: 1,
        position_rank: 1,
        roster_percent: nil,
        trade_frequency: nil,
        draft_year: nil,
        as_of: DateTime.utc_now() |> DateTime.truncate(:second)
      }
    ])
  end

  # I am deep at RB and thin at WR; they are the mirror image.
  @mine_rbs ~w(1001 1002 1003 1004)
  @mine_wrs ~w(1005 1006)
  @their_wrs ~w(2001 2002 2003 2004)
  @their_rbs ~w(2005 2006)

  defp seed_board do
    Enum.each(@mine_rbs ++ @their_rbs, &seed_player(&1, "RB"))
    Enum.each(@mine_wrs ++ @their_wrs, &seed_player(&1, "WR"))
    Enum.each(@mine_rbs ++ @mine_wrs ++ @their_wrs ++ @their_rbs, &seed_value(&1, 5000.0))
  end

  defp stub_league(bypass, opts \\ []) do
    rosters =
      Keyword.get(opts, :rosters, [
        %{"owner_id" => @me, "roster_id" => 1, "players" => @mine_rbs ++ @mine_wrs},
        %{"owner_id" => @them, "roster_id" => 2, "players" => @their_wrs ++ @their_rbs}
      ])

    Bypass.stub(bypass, "GET", "/league/#{@league}/rosters", fn conn ->
      Plug.Conn.resp(conn, 200, Jason.encode!(rosters))
    end)

    Bypass.stub(bypass, "GET", "/league/#{@league}/users", fn conn ->
      Plug.Conn.resp(
        conn,
        200,
        Jason.encode!([
          %{"user_id" => @me, "display_name" => "me"},
          %{"user_id" => @them, "display_name" => "babaghanoush123"}
        ])
      )
    end)

    # The 2027 draft has not happened, so 2027 picks are tradeable; 2026's is
    # complete, which is what stops a spent pick being offered.
    Bypass.stub(bypass, "GET", "/league/#{@league}/drafts", fn conn ->
      Plug.Conn.resp(
        conn,
        200,
        Jason.encode!(Keyword.get(opts, :drafts, [%{"season" => "2026", "status" => "complete"}]))
      )
    end)

    Bypass.stub(bypass, "GET", "/league/#{@league}/traded_picks", fn conn ->
      Plug.Conn.resp(conn, 200, Jason.encode!(Keyword.get(opts, :traded, [])))
    end)

    Bypass.stub(bypass, "GET", "/league/#{@league}", fn conn ->
      Plug.Conn.resp(
        conn,
        200,
        Jason.encode!(%{"roster_positions" => ~w(QB RB RB WR WR TE BN BN BN BN)})
      )
    end)
  end

  test "suggests giving depth and getting need", %{bypass: bypass, conn: conn} do
    seed_board()
    stub_league(bypass)

    body = conn |> get(~p"/api/v1/leagues/#{@league}/trades?user_id=#{@me}") |> json_response(200)

    assert body["source"] == "keeptradecut:sf"
    assert [first | _] = body["suggestions"]
    assert first["partnerName"] == "babaghanoush123"
    assert Enum.all?(first["give"], &(&1 in @mine_rbs))
    assert Enum.all?(first["get"], &(&1 in @their_wrs))
  end

  test "sends the roster shape it matched on, not just the verdict", %{bypass: bypass, conn: conn} do
    seed_board()
    stub_league(bypass)

    body = conn |> get(~p"/api/v1/leagues/#{@league}/trades?user_id=#{@me}") |> json_response(200)

    # A suggestion claims "you are deep here and thin there"; without these
    # the caller is being asked to trust rather than shown the working.
    assert body["rosterShape"]["depth"] == %{"RB" => 4, "WR" => 2}
    assert body["rosterShape"]["starters"] == %{"QB" => 1, "RB" => 2, "WR" => 2, "TE" => 1}
  end

  test "a manager with no roster in the league is a 404, not an empty list", %{
    bypass: bypass,
    conn: conn
  } do
    # "You are not in this league" and "no trades were found" are different
    # answers and must not render the same.
    seed_board()
    stub_league(bypass)

    body = conn |> get(~p"/api/v1/leagues/#{@league}/trades?user_id=999") |> json_response(404)
    assert body["errors"]["detail"] =~ "no roster in this league"
  end

  test "a missing user_id is a 422 rather than a guess", %{bypass: bypass, conn: conn} do
    seed_board()
    stub_league(bypass)

    assert conn |> get(~p"/api/v1/leagues/#{@league}/trades") |> json_response(422)
  end

  test "superflex=false switches the price list", %{bypass: bypass, conn: conn} do
    seed_board()
    stub_league(bypass)

    body =
      conn
      |> get(~p"/api/v1/leagues/#{@league}/trades?user_id=#{@me}&superflex=false")
      |> json_response(200)

    assert body["source"] == "keeptradecut:1qb"
    # No 1QB values were seeded, so nothing can be priced and nothing is
    # suggested — which is the honest answer, not a fallback to the other list.
    assert body["suggestions"] == []
  end

  test "an upstream failure is a 502 rather than an empty result", %{bypass: bypass, conn: conn} do
    Bypass.stub(bypass, "GET", "/league/#{@league}/rosters", fn conn ->
      Plug.Conn.resp(conn, 500, "boom")
    end)

    assert conn |> get(~p"/api/v1/leagues/#{@league}/trades?user_id=#{@me}") |> json_response(502)
  end

  test "a roster with no owner is not offered as a trade partner", %{bypass: bypass, conn: conn} do
    seed_board()

    stub_league(bypass,
      rosters: [
        %{"owner_id" => @me, "roster_id" => 1, "players" => @mine_rbs ++ @mine_wrs},
        %{"owner_id" => nil, "roster_id" => 3, "players" => @their_wrs}
      ]
    )

    body = conn |> get(~p"/api/v1/leagues/#{@league}/trades?user_id=#{@me}") |> json_response(200)
    assert body["suggestions"] == []
  end
end
